### ISSUE TITLE
When I run setup and then plug my pi into my windows pc, windows says that the recently conected usb device is malfunctioning.

### ISSUE THREAD

**Issue by clonex10100** [c4software/pi-as-keyboard#2]
I know this is an old project, but i'd appreciate any insight into what's going wrong because I would really like to use this.

**Comment by c4software** [comment]
Hi,

What's your Kernel version ? (You can see it with the command uname -a)

**Comment by NicholasJCameron** [comment]
Ok I got the keyboard to output some characters by releasing the keypress (code below)

echo -ne "\x06" > /dev/hidg0
echo -ne "\x00\x00\x00\x00\x00\x00\x00" > /dev/hidg0

however I am unable to output the character g...I have done some reading and it is saying because the hid keycode 0x0a is also used as a new line character and raspberry pi may be getting confused..

any insight?

**Comment by NicholasJCameron** [comment]
raspberry pi zero w

**Comment by clonex10100** [comment]
I had that same issue. I ended up opening the /dev/hidg0 using a c program instead of just using echo.

**Comment by c4software** [comment]
Hi,

Interesting, on Windows too ?

**Comment by NicholasJCameron** [comment]
/bin/echo will work...its because 0x0A is linux bash for nl as well

On Tue, Mar 13, 2018 at 5:47 PM, Brosseau Valentin <notifications@github.com

**Comment by NicholasJCameron** [comment]
I've got an odd issue, windows 98 computer is not recognizing the hid device?
Any thoughts?

**Comment by c4software** [comment]
Windows 98 oO. No clue! Windows 98 usb HID management is special... I'm not really sure if it's will be working.

Certainly need a driver
